// <auto-generated />
namespace ArcheageCraft.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Unique_Item_Constraint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Unique_Item_Constraint));
        
        string IMigrationMetadata.Id
        {
            get { return "201411151839477_Unique_Item_Constraint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
