// <auto-generated />
namespace ArcheageCraft.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class price_metadata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(price_metadata));
        
        string IMigrationMetadata.Id
        {
            get { return "201411152218079_price_metadata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
